const mongoose = require('mongoose');
const Schema   = mongoose.Schema;

const articleSchema = new Schema({
  source: Object,
  author: String,
  title: String,
  description: String,
  url: String,
  urlToImage: String,
  publishedAt: Date,
  content: String
});

module.exports = mongoose.model('Article', articleSchema);






//single article: 

// { source: { id: null, name: 'Phonearena.com' },
//   author: 'Alan Friedman',
//   title:
//    'Apple iPhone users escape bug that would have forced them to factory resrt their phone - Phone Arena',
//   description:
//    'The iOS 12.3 update disseminated in May fixed a bug that could have forced Apple iPhone users to factory reset their phone after receiving a particular malformed iMessage.',
//   url:
//    'https://www.phonearena.com/news/Exterminated-bug-could-have-forced-iPhone-users-to-factory-reset-their-device_id117310',
//   urlToImage:
//    'https://i-cdn.phonearena.com/images/article/117310-two_lead/Apple-iPhone-users-escape-bug-that-would-have-forced-them-to-factory-resrt-their-phone.jpg',
//   publishedAt: '2019-07-07T05:23:47Z',
//   content:
//    'All content, features, and design are Copyright 2001-2019 PhoneArena.com. All rights reserved. Reproduction in whole or in part or in any form or medium without written permission is prohibited!' }

//General queue
// { status: 200,
//   statusText: 'OK',
//   headers:
//    { 'cache-control': 'no-cache',
//      pragma: 'no-cache',
//      'content-length': '16948',
//      'content-type': 'application/json; charset=utf-8',
//      expires: '-1',
//      'x-cached-result': 'false',
//      'access-control-allow-origin': '*',
//      'access-control-allow-methods': 'GET',
//      'access-control-allow-headers': 'x-api-key, authorization',
//      date: 'Sun, 07 Jul 2019 05:53:55 GMT',
//      connection: 'close' },
//   config:
//    { url:
//       'https://newsapi.org/v2/top-headlines?country=us&apiKey=d27e647a6e484e358a50c1089f09ecae',
//      headers:
//       { Accept: 'application/json, text/plain, */*',
//         'User-Agent': 'axios/0.19.0' },
//      transformRequest: [ [Function: transformRequest] ],
//      transformResponse: [ [Function: transformResponse] ],
//      timeout: 0,
//      adapter: [Function: httpAdapter],
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      method: 'get',
//      data: undefined },
//   request:
//    ClientRequest {
//      _events:
//       [Object: null prototype] {
//         socket: [Function],
//         abort: [Function],
//         aborted: [Function],
//         error: [Function],
//         timeout: [Function],
//         prefinish: [Function: requestOnPrefinish] },
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedConnection: false,
//      _removedContLen: false,
//      _removedTE: false,
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket:
//       TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         _SNICallback: null,
//         servername: 'newsapi.org',
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object],
//         _eventsCount: 8,
//         connecting: false,
//         _hadError: false,
//         _handle: [TLSWrap],
//         _parent: null,
//         _host: 'newsapi.org',
//         _readableState: [ReadableState],
//         readable: true,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         writable: false,
//         allowHalfOpen: false,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: [TLSWrap],
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular],
//         [Symbol(res)]: [TLSWrap],
//         [Symbol(asyncId)]: 16,
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(connect-options)]: [Object] },
//      connection:
//       TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         _SNICallback: null,
//         servername: 'newsapi.org',
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object],
//         _eventsCount: 8,
//         connecting: false,
//         _hadError: false,
//         _handle: [TLSWrap],
//         _parent: null,
//         _host: 'newsapi.org',
//         _readableState: [ReadableState],
//         readable: true,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         writable: false,
//         allowHalfOpen: false,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: [TLSWrap],
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular],
//         [Symbol(res)]: [TLSWrap],
//         [Symbol(asyncId)]: 16,
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: null,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(connect-options)]: [Object] },
//      _header:
//       'GET /v2/top-headlines?country=us&apiKey=d27e647a6e484e358a50c1089f09ecae HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: newsapi.org\r\nConnection: close\r\n\r\n',
//      _onPendingData: [Function: noopPendingOutput],
//      agent:
//       Agent {
//         _events: [Object],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         defaultPort: 443,
//         protocol: 'https:',
//         options: [Object],
//         requests: {},
//         sockets: [Object],
//         freeSockets: {},
//         keepAliveMsecs: 1000,
//         keepAlive: false,
//         maxSockets: Infinity,
//         maxFreeSockets: 256,
//         maxCachedSessions: 100,
//         _sessionCache: [Object] },
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path:
//       '/v2/top-headlines?country=us&apiKey=d27e647a6e484e358a50c1089f09ecae',
//      _ended: true,
//      res:
//       IncomingMessage {
//         _readableState: [ReadableState],
//         readable: false,
//         _events: [Object],
//         _eventsCount: 3,
//         _maxListeners: undefined,
//         socket: [TLSSocket],
//         connection: [TLSSocket],
//         httpVersionMajor: 1,
//         httpVersionMinor: 1,
//         httpVersion: '1.1',
//         complete: true,
//         headers: [Object],
//         rawHeaders: [Array],
//         trailers: {},
//         rawTrailers: [],
//         aborted: false,
//         upgrade: false,
//         url: '',
//         method: null,
//         statusCode: 200,
//         statusMessage: 'OK',
//         client: [TLSSocket],
//         _consuming: true,
//         _dumped: false,
//         req: [Circular],
//         responseUrl:
//          'https://newsapi.org/v2/top-headlines?country=us&apiKey=d27e647a6e484e358a50c1089f09ecae',
//         redirects: [] },
//      aborted: undefined,
//      timeoutCb: null,
//      upgradeOrConnect: false,
//      parser: null,
//      maxHeadersCount: null,
//      _redirectable:
//       Writable {
//         _writableState: [WritableState],
//         writable: true,
//         _events: [Object],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _options: [Object],
//         _redirectCount: 0,
//         _redirects: [],
//         _requestBodyLength: 0,
//         _requestBodyBuffers: [],
//         _onNativeResponse: [Function],
//         _currentRequest: [Circular],
//         _currentUrl:
//          'https://newsapi.org/v2/top-headlines?country=us&apiKey=d27e647a6e484e358a50c1089f09ecae' },
//      [Symbol(isCorked)]: false,
//      [Symbol(outHeadersKey)]:
//       [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
//   data:
//    { status: 'ok',
//      totalResults: 38,
//      articles:
//       [ [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object] ] } }
        